"""Deterministic lesson contracts for mastery-path tutoring."""

from __future__ import annotations

import json
from typing import Any

from cognispheretutor.learning.policy import NextStep

_BEGINNER_SIGNALS = {
    "beginner",
    "complete beginner",
    "from zero",
    "from scratch",
    "no idea",
    "newbie",
    "零基础",
    "从零",
    "完全不会",
    "新手",
}
_SYSTEMATIC_SIGNALS = {
    "all",
    "complete",
    "comprehensive",
    "full",
    "from start to end",
    "step by step",
    "systematic",
    "系统",
    "全面",
    "完整",
    "从头",
}


def build_lesson_contract_seed(
    *,
    domain: str,
    learner_goal: str,
    next_step: NextStep,
    map_summary: dict[str, Any],
) -> str:
    """Build the platform-owned classroom contract for the current turn.

    Domain facts stay in plugin/KG grounding. This contract only fixes the
    teaching flow: what mode this turn is in, what the model must do next, and
    which deterministic gate controls advancement.
    """
    learner_profile = _learner_profile(learner_goal)
    current = next_step.to_dict()
    current["display_name"] = _objective_label(next_step, domain)
    modules = list(map_summary.get("modules") or [])
    payload = {
        "contract_id": "deeptutor.mastery.lesson_contract.v1",
        "domain": domain,
        "course_goal": _course_goal(domain, learner_goal),
        "learner_profile": learner_profile,
        "path_overview": _path_overview(map_summary),
        "current_objective": current,
        "lesson_mode": _lesson_mode(next_step, learner_profile),
        "must_teach": _must_teach(next_step, modules),
        "must_ask": _must_ask(next_step),
        "check_options": _check_options(next_step),
        "required_check": _required_check(next_step, map_summary),
        "free_response_policy": _free_response_policy(next_step, map_summary),
        "allowed_sources": [
            "deterministic_mastery_status",
            "local_plugin_pack",
            "cognisphere_materialized",
            "plugin_runtime_tools",
        ],
        "advance_rule": _advance_rule(next_step),
        "post_grade_policy": _post_grade_policy(next_step),
        "interaction_policy": _interaction_policy(next_step, learner_profile),
    }
    return (
        "### Mastery Lesson Contract\n"
        "This is a deterministic classroom contract generated by Tutor before "
        "the LLM answered. Follow it over free-form chat instincts. Domain facts "
        "must come from the grounding block; this contract controls the lesson flow.\n"
        f"```json\n{json.dumps(payload, ensure_ascii=False)}\n```"
    )


def _learner_profile(goal: str) -> dict[str, Any]:
    text = goal.lower()
    level = "absolute_beginner" if any(signal in text for signal in _BEGINNER_SIGNALS) else "unknown"
    scope = "systematic_full_path" if any(signal in text for signal in _SYSTEMATIC_SIGNALS) else "current_objective"
    return {"level": level, "requested_scope": scope}


def _course_goal(domain: str, learner_goal: str) -> str:
    goal = learner_goal.strip()
    return goal[:240] if goal else f"Mastery path for {domain}"


def _path_overview(summary: dict[str, Any]) -> dict[str, Any]:
    counts = dict(summary.get("counts") or {})
    modules = []
    for module in list(summary.get("modules") or [])[:10]:
        if not isinstance(module, dict):
            continue
        modules.append(
            {
                "id": module.get("id"),
                "name": module.get("name"),
                "total": module.get("total"),
                "mastered": module.get("mastered"),
                "sample_objectives": [
                    kp.get("name")
                    for kp in list(module.get("knowledge_points") or [])[:5]
                    if isinstance(kp, dict) and kp.get("name")
                ],
            }
        )
    return {
        "total_objectives": counts.get("total"),
        "mastered": counts.get("mastered"),
        "learning": counts.get("learning"),
        "new": counts.get("new"),
        "modules": modules,
    }


def _lesson_mode(next_step: NextStep, learner_profile: dict[str, Any]) -> str:
    if next_step.action == "answer_pending":
        return "grade_pending_answer"
    if next_step.action == "review":
        return "review_then_check"
    if next_step.action == "complete":
        return "summarize_completion"
    if next_step.action == "probe" and learner_profile.get("level") == "absolute_beginner":
        return "teach_then_quick_check"
    if next_step.knowledge_point_type in {"memory", "procedure"}:
        return "quiz_then_grade"
    return "teach_then_quick_check"


def _must_teach(next_step: NextStep, modules: list[Any]) -> list[str]:
    if next_step.action == "complete":
        return ["Summarize mastered objectives and suggest the next path only after the summary."]
    if next_step.action == "answer_pending":
        return ["Do not teach new material; evaluate the learner's pending answer first."]
    items = [
        f"Begin the current objective: {_objective_label(next_step, '')}.",
        "Use the Cognisphere Plugin Graph Grounding block for factual content.",
        "Keep the explanation beginner-friendly and focused on one objective.",
    ]
    if next_step.status == "new":
        items.append("Briefly orient the learner before checking prior knowledge.")
    if modules:
        items.append("Give a compact path overview only if the learner asked for a full/systematic path.")
    return items


def _must_ask(next_step: NextStep) -> str:
    if next_step.action == "answer_pending":
        return "Call mastery_grade with the learner's answer to the pending question."
    if next_step.action == "complete":
        return "No assessment question is required; ask whether the learner wants a new path."
    name = _objective_label(next_step, "")
    if next_step.action == "probe" and "procedure" == next_step.knowledge_point_type:
        return (
            f"After the mini-lesson, immediately register one quick multiple-choice "
            f"check about {name} with mastery_quiz(question_type='choice'), then "
            "present it with ask_user. Do not ask the learner to choose the quiz "
            "format, scope, question content, or options."
        )
    if next_step.knowledge_point_type in {"memory", "procedure"}:
        return (
            f"Create one focused default multiple-choice question for {name} with "
            "mastery_quiz, then present it via ask_user. Do not negotiate the "
            "assessment format with the learner."
        )
    return (
        f"After the mini-lesson, immediately register one quick multiple-choice "
        f"check about {name} with mastery_quiz(question_type='choice'), then "
        "present it with ask_user. Do not ask whether the learner wants a quiz. "
        "Do not ask a second explain-back question after a correct early quick "
        "check unless required_check.mode is free_response."
    )


def _advance_rule(next_step: NextStep) -> str:
    if next_step.action == "answer_pending":
        return "Advance only if mastery_grade reports mastered true."
    if next_step.action == "probe":
        return "Advance only after a later mastery tool call records sufficient evidence."
    if next_step.knowledge_point_type in {"memory", "procedure"}:
        return "Advance only after mastery_quiz + mastery_grade clears the quantitative gate."
    if next_step.action == "complete":
        return "Path is complete; no advancement needed."
    return "Advance only after a later mastery_assess call records passed true."


def _post_grade_policy(next_step: NextStep) -> dict[str, Any]:
    if next_step.action == "answer_pending":
        return {
            "when_mastery_grade_mastered_true": (
                "Give concise feedback, then teach the next objective before any "
                "new mastery_quiz. Do not chain quiz cards without intervening "
                "lesson content."
            ),
            "when_mastery_grade_mastered_false": (
                "Explain the mistake, reteach the same objective briefly, then "
                "register one replacement quick check."
            ),
        }
    return {
        "lesson_first": (
            "For every new objective, the order is mini-lesson -> one quick check "
            "card -> grade. Never start an objective with a quiz unless the "
            "current lesson contract explicitly says review."
        )
    }


def _check_options(next_step: NextStep) -> list[dict[str, str]]:
    if next_step.action in {"answer_pending", "complete"}:
        return []
    if next_step.knowledge_point_type in {"memory", "procedure"}:
        return [
            {
                "mode": "multiple_choice",
                "purpose": "Fast certification-style check; grade with mastery_grade.",
            },
            {
                "mode": "true_false",
                "purpose": "Fast binary misconception check; grade with mastery_grade.",
            },
            {
            "mode": "free_response",
            "purpose": "Optional deep explanation; schedule as required only at mastery checkpoints.",
        },
        ]
    return [
        {
            "mode": "multiple_choice",
            "purpose": "Fast certification-style check for early confidence and pacing.",
        },
        {
            "mode": "true_false",
            "purpose": "Quick misconception check for early confidence and pacing.",
        },
        {
            "mode": "free_response",
            "purpose": "Optional deep explanation only when the learner asks or a checkpoint requires it.",
        },
    ]


def _required_check(next_step: NextStep, summary: dict[str, Any]) -> dict[str, Any]:
    if next_step.action in {"answer_pending", "complete"}:
        return {"mode": "none", "reason": "No new mini-lesson check is needed."}
    if _free_response_required(summary):
        return {
            "mode": "free_response",
            "reason": "The learner is past the foundation ramp; require explain-back to confirm transfer.",
        }
    return {
        "mode": "quick_check",
        "allowed_modes": ["multiple_choice"],
        "default_mode": "multiple_choice",
        "reason": (
            "During early learning, automatically run a certification-style "
            "multiple-choice quick check after each mini-lesson."
        ),
    }


def _free_response_policy(next_step: NextStep, summary: dict[str, Any]) -> dict[str, Any]:
    required = _free_response_required(summary)
    return {
        "required_now": required and next_step.action not in {"answer_pending", "complete"},
        "optional_now": not required and next_step.action not in {"answer_pending", "complete"},
        "when_required": (
            "Require free response after the learner has cleared the foundation ramp, "
            "at review checkpoints, or when quick checks reveal fragile understanding."
        ),
        "instruction": (
            "Do not require or casually add a free-response explain-back while "
            "required_now is false. If a quick check is correct in the early ramp, "
            "give concise feedback and continue with the next objective's mini-lesson."
        ),
    }


def _free_response_required(summary: dict[str, Any]) -> bool:
    counts = dict(summary.get("counts") or {})
    try:
        total = int(counts.get("total") or 0)
        mastered = int(counts.get("mastered") or 0)
    except (TypeError, ValueError):
        return False
    if total <= 0:
        return False
    return mastered >= 3 and mastered / total >= 0.15


def _interaction_policy(next_step: NextStep, learner_profile: dict[str, Any]) -> list[str]:
    policy = [
        "Do not end the turn by asking the learner to choose a topic from a menu.",
        "Do not ask the learner to choose the assessment format; use the default quick multiple-choice check.",
        "Do not create a new unified_* path.",
        "For each objective, teach a substantive mini-lesson before registering its quick check.",
        "After the mini-lesson, immediately register and present one quick multiple-choice check.",
        "After grading a previous objective as mastered, do not chain directly into another quiz; teach the next mini-lesson first.",
        "Free response is optional only when the learner asks for it; do not add it after a correct early quick check unless free_response_policy.required_now is true.",
        "Do not mark qualitative mastery in the same turn as the initial explanation.",
    ]
    if learner_profile.get("level") == "absolute_beginner":
        policy.append("Assume no prior vocabulary; define unavoidable terms plainly.")
    if next_step.action in {"probe", "assess"}:
        policy.append(
            "End with one quick-check question, not another methodology explanation."
        )
    return policy


def _objective_label(next_step: NextStep, domain: str) -> str:
    name = (next_step.knowledge_point_name or next_step.knowledge_point_id or "").strip()
    lowered = _normalize_label(name)
    domain_text = _normalize_label(domain)
    if not name:
        return "the current objective"
    if "cognisphere" in lowered and (not domain_text or domain_text in lowered):
        return "the learning path overview"
    return name


def _normalize_label(text: str) -> str:
    return str(text or "").replace("_", " ").replace("-", " ").strip().lower()


__all__ = ["build_lesson_contract_seed"]
